# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/odahim/Sources/GitHub/trat

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/odahim/Sources/GitHub/trat

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/odahim/Sources/GitHub/trat/CMakeFiles /home/odahim/Sources/GitHub/trat//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/odahim/Sources/GitHub/trat/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named trat_bot

# Build rule for target.
trat_bot: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 trat_bot
.PHONY : trat_bot

# fast build rule for target.
trat_bot/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trat_bot.dir/build.make CMakeFiles/trat_bot.dir/build
.PHONY : trat_bot/fast

src/Bot/bot.o: src/Bot/bot.cpp.o
.PHONY : src/Bot/bot.o

# target to build an object file
src/Bot/bot.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trat_bot.dir/build.make CMakeFiles/trat_bot.dir/src/Bot/bot.cpp.o
.PHONY : src/Bot/bot.cpp.o

src/Bot/bot.i: src/Bot/bot.cpp.i
.PHONY : src/Bot/bot.i

# target to preprocess a source file
src/Bot/bot.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trat_bot.dir/build.make CMakeFiles/trat_bot.dir/src/Bot/bot.cpp.i
.PHONY : src/Bot/bot.cpp.i

src/Bot/bot.s: src/Bot/bot.cpp.s
.PHONY : src/Bot/bot.s

# target to generate assembly for a file
src/Bot/bot.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trat_bot.dir/build.make CMakeFiles/trat_bot.dir/src/Bot/bot.cpp.s
.PHONY : src/Bot/bot.cpp.s

src/Bot/handling.o: src/Bot/handling.cpp.o
.PHONY : src/Bot/handling.o

# target to build an object file
src/Bot/handling.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trat_bot.dir/build.make CMakeFiles/trat_bot.dir/src/Bot/handling.cpp.o
.PHONY : src/Bot/handling.cpp.o

src/Bot/handling.i: src/Bot/handling.cpp.i
.PHONY : src/Bot/handling.i

# target to preprocess a source file
src/Bot/handling.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trat_bot.dir/build.make CMakeFiles/trat_bot.dir/src/Bot/handling.cpp.i
.PHONY : src/Bot/handling.cpp.i

src/Bot/handling.s: src/Bot/handling.cpp.s
.PHONY : src/Bot/handling.s

# target to generate assembly for a file
src/Bot/handling.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trat_bot.dir/build.make CMakeFiles/trat_bot.dir/src/Bot/handling.cpp.s
.PHONY : src/Bot/handling.cpp.s

src/Bot/listen.o: src/Bot/listen.cpp.o
.PHONY : src/Bot/listen.o

# target to build an object file
src/Bot/listen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trat_bot.dir/build.make CMakeFiles/trat_bot.dir/src/Bot/listen.cpp.o
.PHONY : src/Bot/listen.cpp.o

src/Bot/listen.i: src/Bot/listen.cpp.i
.PHONY : src/Bot/listen.i

# target to preprocess a source file
src/Bot/listen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trat_bot.dir/build.make CMakeFiles/trat_bot.dir/src/Bot/listen.cpp.i
.PHONY : src/Bot/listen.cpp.i

src/Bot/listen.s: src/Bot/listen.cpp.s
.PHONY : src/Bot/listen.s

# target to generate assembly for a file
src/Bot/listen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trat_bot.dir/build.make CMakeFiles/trat_bot.dir/src/Bot/listen.cpp.s
.PHONY : src/Bot/listen.cpp.s

src/Bot/sending.o: src/Bot/sending.cpp.o
.PHONY : src/Bot/sending.o

# target to build an object file
src/Bot/sending.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trat_bot.dir/build.make CMakeFiles/trat_bot.dir/src/Bot/sending.cpp.o
.PHONY : src/Bot/sending.cpp.o

src/Bot/sending.i: src/Bot/sending.cpp.i
.PHONY : src/Bot/sending.i

# target to preprocess a source file
src/Bot/sending.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trat_bot.dir/build.make CMakeFiles/trat_bot.dir/src/Bot/sending.cpp.i
.PHONY : src/Bot/sending.cpp.i

src/Bot/sending.s: src/Bot/sending.cpp.s
.PHONY : src/Bot/sending.s

# target to generate assembly for a file
src/Bot/sending.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trat_bot.dir/build.make CMakeFiles/trat_bot.dir/src/Bot/sending.cpp.s
.PHONY : src/Bot/sending.cpp.s

src/Bot/telegramNetworking.o: src/Bot/telegramNetworking.cpp.o
.PHONY : src/Bot/telegramNetworking.o

# target to build an object file
src/Bot/telegramNetworking.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trat_bot.dir/build.make CMakeFiles/trat_bot.dir/src/Bot/telegramNetworking.cpp.o
.PHONY : src/Bot/telegramNetworking.cpp.o

src/Bot/telegramNetworking.i: src/Bot/telegramNetworking.cpp.i
.PHONY : src/Bot/telegramNetworking.i

# target to preprocess a source file
src/Bot/telegramNetworking.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trat_bot.dir/build.make CMakeFiles/trat_bot.dir/src/Bot/telegramNetworking.cpp.i
.PHONY : src/Bot/telegramNetworking.cpp.i

src/Bot/telegramNetworking.s: src/Bot/telegramNetworking.cpp.s
.PHONY : src/Bot/telegramNetworking.s

# target to generate assembly for a file
src/Bot/telegramNetworking.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trat_bot.dir/build.make CMakeFiles/trat_bot.dir/src/Bot/telegramNetworking.cpp.s
.PHONY : src/Bot/telegramNetworking.cpp.s

src/Bot/work.o: src/Bot/work.cpp.o
.PHONY : src/Bot/work.o

# target to build an object file
src/Bot/work.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trat_bot.dir/build.make CMakeFiles/trat_bot.dir/src/Bot/work.cpp.o
.PHONY : src/Bot/work.cpp.o

src/Bot/work.i: src/Bot/work.cpp.i
.PHONY : src/Bot/work.i

# target to preprocess a source file
src/Bot/work.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trat_bot.dir/build.make CMakeFiles/trat_bot.dir/src/Bot/work.cpp.i
.PHONY : src/Bot/work.cpp.i

src/Bot/work.s: src/Bot/work.cpp.s
.PHONY : src/Bot/work.s

# target to generate assembly for a file
src/Bot/work.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trat_bot.dir/build.make CMakeFiles/trat_bot.dir/src/Bot/work.cpp.s
.PHONY : src/Bot/work.cpp.s

src/Shell/shell.o: src/Shell/shell.cpp.o
.PHONY : src/Shell/shell.o

# target to build an object file
src/Shell/shell.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trat_bot.dir/build.make CMakeFiles/trat_bot.dir/src/Shell/shell.cpp.o
.PHONY : src/Shell/shell.cpp.o

src/Shell/shell.i: src/Shell/shell.cpp.i
.PHONY : src/Shell/shell.i

# target to preprocess a source file
src/Shell/shell.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trat_bot.dir/build.make CMakeFiles/trat_bot.dir/src/Shell/shell.cpp.i
.PHONY : src/Shell/shell.cpp.i

src/Shell/shell.s: src/Shell/shell.cpp.s
.PHONY : src/Shell/shell.s

# target to generate assembly for a file
src/Shell/shell.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trat_bot.dir/build.make CMakeFiles/trat_bot.dir/src/Shell/shell.cpp.s
.PHONY : src/Shell/shell.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trat_bot.dir/build.make CMakeFiles/trat_bot.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trat_bot.dir/build.make CMakeFiles/trat_bot.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trat_bot.dir/build.make CMakeFiles/trat_bot.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/networking.o: src/networking.cpp.o
.PHONY : src/networking.o

# target to build an object file
src/networking.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trat_bot.dir/build.make CMakeFiles/trat_bot.dir/src/networking.cpp.o
.PHONY : src/networking.cpp.o

src/networking.i: src/networking.cpp.i
.PHONY : src/networking.i

# target to preprocess a source file
src/networking.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trat_bot.dir/build.make CMakeFiles/trat_bot.dir/src/networking.cpp.i
.PHONY : src/networking.cpp.i

src/networking.s: src/networking.cpp.s
.PHONY : src/networking.s

# target to generate assembly for a file
src/networking.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trat_bot.dir/build.make CMakeFiles/trat_bot.dir/src/networking.cpp.s
.PHONY : src/networking.cpp.s

src/parser.o: src/parser.cpp.o
.PHONY : src/parser.o

# target to build an object file
src/parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trat_bot.dir/build.make CMakeFiles/trat_bot.dir/src/parser.cpp.o
.PHONY : src/parser.cpp.o

src/parser.i: src/parser.cpp.i
.PHONY : src/parser.i

# target to preprocess a source file
src/parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trat_bot.dir/build.make CMakeFiles/trat_bot.dir/src/parser.cpp.i
.PHONY : src/parser.cpp.i

src/parser.s: src/parser.cpp.s
.PHONY : src/parser.s

# target to generate assembly for a file
src/parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trat_bot.dir/build.make CMakeFiles/trat_bot.dir/src/parser.cpp.s
.PHONY : src/parser.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... trat_bot"
	@echo "... src/Bot/bot.o"
	@echo "... src/Bot/bot.i"
	@echo "... src/Bot/bot.s"
	@echo "... src/Bot/handling.o"
	@echo "... src/Bot/handling.i"
	@echo "... src/Bot/handling.s"
	@echo "... src/Bot/listen.o"
	@echo "... src/Bot/listen.i"
	@echo "... src/Bot/listen.s"
	@echo "... src/Bot/sending.o"
	@echo "... src/Bot/sending.i"
	@echo "... src/Bot/sending.s"
	@echo "... src/Bot/telegramNetworking.o"
	@echo "... src/Bot/telegramNetworking.i"
	@echo "... src/Bot/telegramNetworking.s"
	@echo "... src/Bot/work.o"
	@echo "... src/Bot/work.i"
	@echo "... src/Bot/work.s"
	@echo "... src/Shell/shell.o"
	@echo "... src/Shell/shell.i"
	@echo "... src/Shell/shell.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/networking.o"
	@echo "... src/networking.i"
	@echo "... src/networking.s"
	@echo "... src/parser.o"
	@echo "... src/parser.i"
	@echo "... src/parser.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

