/* trat/src/Shell/shell.cpp */

#include "../../include/shell.hpp"
#include <cstring>

#define CURRENT_PATH std::filesystem::current_path().string().c_str() 

namespace trat 
{
  void ShellResponse_destroy(ShellResponse *P_Shell_Response)
  {
    if (P_Shell_Response -> response != nullptr)
    {
      free(P_Shell_Response -> response);
      P_Shell_Response -> response = nullptr;
    }
  } 

  Shell::Shell(trat::Bot* P_Master_Bot) : masterBot(P_Master_Bot) {}
  /* To be freed */
  char* Shell::getCurrentPath() 
  {
    return strdup(CURRENT_PATH); 
  }

  bool Shell::executeShellCommandWithoutResponse(const char* Command) 
  {
    return std::system(Command) == 0;
  }

  /*Honestly I do not understand this part of code, this was generated by ChatGpt, I need to remove the try catch syntax from my C++ code, because it is ugly.
   *
   *
   */
  ShellResponse Shell::executeShellCommand(const char* Command) 
  {
    ShellResponse shell_response;
    shell_response.isSuccessful = true;
    std::string result; // Ensure the memory is valid across calls
    std::mutex result_mutex; // Mutex to guard access to the result
    std::unique_lock<std::mutex> lock(result_mutex); // Lock during updates
    result.clear(); // Clear any previous result
    try 
    {
      boost::process::ipstream pipe_stream;
      boost::process::child process(Command, boost::process::std_out > pipe_stream);

      std::ostringstream oss;
      std::string line;

      while (pipe_stream && std::getline(pipe_stream, line))
      {
        oss << line << '\n';
      }
      process.wait();
      result = oss.str();

    }catch (const std::exception& e) 
    {
      result = "Error: ";
      result += e.what();
      shell_response.isSuccessful = false;
    }
      shell_response.response = strdup(result.c_str());
      return shell_response;
    }

    bool isExecutable(const char* File_Name)
    {
      if(File_Name != nullptr)
      {
        auto extension = parser::getFileExtensionFromName(File_Name);
        if (strcmp(extension , "sh") == 0 )
        {
          return true;
        }
        return false;
      }
      return false;
    }
} // namespace trat
